apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ntnxInitConfigMap.name }}
  namespace: {{ .Values.ntnxInitConfigMap.namespace }}
data:
  supportedPCVersions: {{ .Values.supportedPCVersions }}
  kubernetesClusterDeploymentType: {{ .Values.kubernetesClusterDeploymentType }}
